#!perl

use lib("../../lib/perl");
use Starmade::Base;

use lib ("./lib");
use marauders_lib;

my $stard_home = "./../..";

starmade_setup_lib_env($stard_home);
my $CONFIG = "./marauders.conf";


main(@ARGV);
sub main {
	my $player = shift(@_);


	if (@{list_ship_objects($player)}) {
		player_defeat($player);
	}

	sleep 30;
	clean_far_objects();
}
