#!perl
package regression;
use strict;
use warnings;

use lib("../../lib/perl");
use Stard::Base;
use Starmade::Base;
use Starmade::Message;
		
use lib("./lib");
use core_reg;
use general_reg;
use player_reg;
use faction_reg;
use sector_reg;
use map_reg;
use plugin_reg;
use multiplexer_reg;
use interactive_reg;

$| = 1;
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
#1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
#2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
#3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# StarMade™ is a registered trademark of Schine GmbH (All Rights Reserved)*
# The makers of stard make no claim of ownership or relationship with the owners of StarMade

## regression
# This script includes the primary regression testing code for stard.
# This script is called to test the stard standard library's functions for 
# defects.

## setup environment
my $debug_home = '.';
my $stard_home = "$debug_home/../..";
my $stard_plugins = "$stard_home/plugins";


starmade_setup_lib_env($stard_home);
stard_setup_lib_env($stard_home);
starmade_stdlib_set_debug(2);


my $player = $ARGV[0];


main(@ARGV);
exit(0);

#################################################

sub main {
	my $player = $_[0];
	my $test = $_[1];

	starmade_broadcast("Regression requested...");

	if (!$test || $test eq 'full') {
		starmade_broadcast("Running full suite");
		stard_core_reg($player);
		general_reg($player);
		player_reg($player);
		faction_reg($player);
		sector_reg($player);
		map_reg($player);
		plugin_reg($player);
		multiplexer_reg($player);
	}
	elsif ($test eq "core") {
		stard_core_reg($player);
	}
	elsif ($test eq "general") {
		general_reg($player);
	}
	elsif ($test eq "player") {
		player_reg($player);
	}
	elsif ($test eq "faction") {
		faction_reg($player);
	}
	elsif ($test eq "sector") {
		sector_reg($player);
	}
	elsif ($test eq "map") {
		map_reg($player);
	}
	elsif ($test eq "plugin") {
		plugin_reg($player);
	}
	elsif ($test eq 'multiplexer') {
		multiplexer_reg($player);
	}
	elsif ($test eq 'interactive') {
		interactive_reg($player);
	}
	else {
		starmade_pm($player, "Error, requested regression suite not found: $test");
		starmade_pm($player, "Available suites:\nall\ncore\ngeneral\nplayer\nfaction\nsector\nmap\nmultiplexer\nplugin\ninteractive");
		exit 0;
	};
	starmade_broadcast("All tests passed!");
}

