#!perl
use strict;
use warnings;

use lib("./lib");
use lib("../../lib");
use stard_lib;
use stard_core;
use bank_lib;

#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
#1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
#2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
#3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

## setup environment
my $stard_home = "./../..";

stard_setup_run_env($stard_home);


main(@ARGV);
exit 0;
#########################################################




sub main {
	my $player = $_[0];
	my $amount = $_[1];
	my $in_bank;
	my $player_credits;

	if (!($amount) || ($amount =~/\D+/ && !($amount eq 'all'))) {
		stard_pm($player, "You must provide the number to deposit!");
		usage($player);
		exit 1;
	};
	$player_credits = get_player_credits($player);
	if ($amount eq 'all') {
		$amount = $player_credits;
	};



	## lock to perform transaction 
	# and gather all data
	my $lock_fh = bank_lock_account($player);
	$in_bank = bank_get_balance($player);
	if (!$lock_fh) {
		stard_pm($player, "FAILED COMMAND: failed to get lock on $player\'s bank account: $?\n");
		exit 1;
	};


	## validate player gas the credits they think they do
	if ($player_credits < $amount) {
		stard_pm($player, "You do not have that many credits to deposit!");
		exit 1;
	};



	## perform transaction
	if (!stard_give_credits($player, "-$amount")) {
		stard_pm($player, "Deposit failed...");
		exit 0;
	};

	if(!bank_add_amount($player, $amount)) {
		stard_pm($player, "Deposit failed...");
		stard_give_credits($player, "$amount");
		exit 0;
	};
	bank_unlock_account($lock_fh);
	stard_pm($player, "$player, $amount has been deposited into your account");
};

## usage
# Print help information
# INPUT1: player to send help message to
sub usage {
	my $player = $_[0];
	stard_pm($player, "Usage: deposit <amount>");
	stard_pm($player, "Description: deposit credits into your bank.");
}
