#!perl
use strict;
use warnings;


use lib("../../lib");
use stard_lib;

use lib ("./lib");
use marauders_lib;

my $stard_home = "./../..";
my $starmade_home = "$stard_home/../StarMade/";


stard_setup_run_env($stard_home);
my $CONFIG = "./marauders.conf";
my $FACTION_ID= -1;
my $demand_restart = 0;

opendir(my $dh, "./blueprints") or warn "Failed to open './blueprints': $!\n";
my @files;
while (readdir($dh)) {
        if ($_ ne '.' && $_ ne '..') {
                push(@files, $_);
        }
}
closedir($dh);

FILE: foreach my $file (@files) {
	if (-d "$starmade_home/blueprints/$file") {
		next FILE;
	}
	system('rsync', '-arv', "./blueprints/$file", "$starmade_home/blueprints/");
	$demand_restart = 1;
}

sleep 10;
clean_old_objects();

while (1) {
	my %player_list = %{stard_player_list()};

	clean_far_objects();
	foreach my $player (keys %player_list) {
		signal_potential_attack($player);
	}
	if ($demand_restart) {
		stard_broadcast("Marauders plugin has installed new blueprints. You will need to restart StarMade in order for Marauders to work correctly.");
	}

	sleep 300;
}
