#!perl
$| = 1;

## setup environment
our $debug_home;
{
	my @tmp = split("/", $0);
	# grab everything but the last entry
	for (my $i = 0; $i < @tmp -1; $i++ ) {
		$debug_home .= "/$tmp[$i]";
	}
	$debug_home =~s/^\///;
}

my $stard_home = "$debug_home/../..";
require "$stard_home/lib/stard_lib.pm";
stard_setup_run_env($stard_home);


while ( 1 == 1 ) {
	stard_broadcast("debug deamon test");
	sleep 60;
}

