#!perl
use strict;
use warnings;

use lib("../../lib/perl");
use Starmade::Message;
use Starmade::Player;

#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
#1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
#2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
#3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# StarMade™ is a registered trademark of Schine GmbH (All Rights Reserved)*
# The makers of stard make no claim of ownership or relationship with the owners of StarMade

## setup environment
my $base_home = '.';
my $base_spool = "$base_home/spool";
my $stard_home = "$base_home/../..";

starmade_setup_lib_env($stard_home);



main(@ARGV);
exit 0;
##############################################



sub main {
	my $player = $_[0];
	my $command;

	starmade_run_if_admin($player);
	if ($_[1]) {
		$command = $_[1];
	}
	else {
		help($player);
		exit 1;
	}


	if ($command eq 'restart') {
		starmade_broadcast("Restarting stard backend. Commands may not function during this time!");
		my @out = `../../bin/stard_daemons restart`;
		print "backend restart requested by '$player'\n";
		print "@out";
		starmade_pm($player, join("", @out));
		
		starmade_broadcast("Restart Complete! Commands should again be functional");
	}
	elsif ( $command eq 'status') {
		my @out = `../../bin/stard_daemons status`;
		print "backend status requested by '$player'\n";
		print "@out";
		starmade_pm($player, "Stard Status:\n" . join("", @out));
		
	}
	else {
		help($player);
		exit 1;
	}
};	

sub help {
	my $player= $_[0];
	my $output = '';
	
	$output .= "usage: !stard [command]\n";
	$output .= "\n";
	$output .= "Commands:\n";
	$output .= "    status - get the current status of stard\n";
	$output .= "    restart - restarts the stard backend. Reloading all mods. Note: commands will not work while restarting\n";
	starmade_pm($player, $output);
}
