#!perl

use lib("../../lib/perl");
use Starmade::Base;

use lib ("./lib");
use marauders_lib;

my $stard_home = "./../..";

starmade_setup_lib_env($stard_home);
my $CONFIG = "./marauders.conf";


main(@ARGV);
sub main {
	shift(@_);
	my $player = shift(@_);

	signal_potential_attack($player);
}
